[build]
  publish = ".next"
  command = "npm install --force && npm run build"

  # Netlify Functions should live under netlify/functions,
  # so they don't clash with our Firebase Cloud Functions folder.
  functions = "netlify/functions"

[build.environment]
  NODE_VERSION = "18"
  NODE_OPTIONS = "--max_old_space_size=4096"
  NEXTJS_MAX_WORKERS = "1"
  SWC_MINIFY = "false"
  DISABLE_IMAGE_OPTIMIZATION = "1"
